import { CritiqueResult } from "../types";

export function generateMarkdownReport(r: CritiqueResult, role: string, level: string): string {
  const recruiter = r.recruiterScan
    ? `\n## Recruiter 15-Sec Scan (Simulation)
* **Would Shortlist:** ${r.recruiterScan.wouldShortlist}
* **Key Observations:**
${r.recruiterScan.reasons.map((r) => `  - ${r}`).join("\n")}`
    : "";

  const kwMatch = r.jobDescriptionMatch
    ? `\n## Job Description Keywords Match
* **Found Keywords:** ${r.jobDescriptionMatch.foundKeywords.join(", ") || "None"}
* **Missing Keywords:** ${r.jobDescriptionMatch.missingKeywords.join(", ") || "None"}`
    : "";

  const metricsInfo = r.metrics
    ? `\n## Content Metrics Analysis
* **Average Bullet Length:** ${r.metrics.averageBulletLength} words
* **Active Action Verbs Used:** ${r.metrics.actionVerbsCount}
* **Weak Verbs Found:** ${r.metrics.weakVerbs.join(", ") || "None"}
* **Passive Voice Instances:** ${r.metrics.passiveVoiceCount}
* **Numbers/Quantification Used:** ${r.metrics.numbersUsedCount} bullets
* **Readability Level:** ${r.metrics.readabilityScore}`
    : "";

  return `# ResumePilot — Critique Report
**Target Role:** ${role}
**Experience Level:** ${level}
**Overall Score:** ${r.score}/100

## Score Breakdown
* **Impact & Achievements:** ${r.scores.impact}/100
* **Layout & Formatting:** ${r.scores.formatting}/100
* **Brevity & Action Verbs:** ${r.scores.brevity}/100
* **ATS Compatibility:** ${r.scores.atsScore}/100

## Executive Summary
${r.summary}
${recruiter}
${kwMatch}
${metricsInfo}

## Core Strengths
${r.strengths.map((s) => `- ${s}`).join("\n")}

## Recommended Improvements
${r.weaknesses
  .map(
    (w, i) => `
### Improvement #${i + 1}: ${w.category}
* **The Problem:** ${w.problem}
* **Actionable Correction:** ${w.suggestion}
* **Before (Draft):** "${w.before}"
* **After (AI Enhanced):** "${w.after}"`
  )
  .join("\n")}

## ATS Parsing Roadblocks
${r.atsReport.issues.length > 0
  ? r.atsReport.issues.map((issue) => `* **Issue:** ${issue}`).join("\n")
  : "* No major technical ATS formatting hurdles detected!"}

## Key Recommended Keywords
${r.atsReport.recommendedKeywords.map((kw) => `* ${kw}`).join("\n")}

## Section-By-Section Feedback
${r.sectionFeedback
  .map(
    (sect) => `### ${sect.sectionName} (${sect.rating})
${sect.detailedFeedback}`
  )
  .join("\n\n")}

## Role Strategy Strategic Tips
${r.tailoredRoleTips}

---
Generated by ResumePilot Advisor — Elevate Your Career Search with AI.`;
}
